/* ALAMKAROK MVP - plain JS so it can be deployed as a static site. */
const cfg = window.JUKEBOX_CONFIG || {};
const app = document.getElementById('app');
const sbReady = cfg.SUPABASE_URL && !cfg.SUPABASE_URL.includes('PASTE_') && cfg.SUPABASE_ANON_KEY && !cfg.SUPABASE_ANON_KEY.includes('PASTE_');
const supabase = sbReady ? window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY) : null;
const colors=['#9b5cff','#28a8ff','#18c9a0','#ff9d2e','#ff4f5f','#f1d21b','#ef67c7','#7bd66f','#54d8e8','#ff6f9c'];
const state={room:null,me:null,people:[],queue:[],isHost:false,channel:null,player:null,playerReady:false,videoApiReady:false,localPosition:0,modal:false};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function code(){return Math.random().toString(36).slice(2,7).toUpperCase();}
function ytId(url){try{const u=new URL(url); if(u.hostname.includes('youtu.be')) return u.pathname.slice(1).split('/')[0]; if(u.hostname.includes('youtube.com')) return u.searchParams.get('v')||u.pathname.split('/').pop();}catch{} return null;}
function ytThumb(id){return `https://i.ytimg.com/vi/${encodeURIComponent(id)}/hqdefault.jpg`;}
function roomUrl(c){return `${location.origin}${location.pathname}?room=${encodeURIComponent(c)}`;}
function renderHome(){app.innerHTML=`<div class="wrap"><div class="hero card"><div class="brand">ALAMKAROK</div><h1 class="h1">Shared YouTube room.</h1><p class="sub">One phone plays the video. Everyone joins, adds to the queue, and controls playback.</p>${!sbReady?'<div class="notice error">Supabase is not configured yet. Fill in <b>config.js</b> after creating your Supabase project.</div>':''}<div class="joinbox"><button class="btn primary" id="create">Create Room</button><div class="small">or join an existing room</div><div class="row"><input class="input" id="roomCode" maxlength="5" placeholder="Room code e.g. 7K4P9" style="flex:1;text-transform:uppercase"><button class="btn" id="joinCode">Join</button></div></div></div><div class="footer">ALAMKAROK MVP • real-time shared queue</div></div>`; if(sbReady){document.getElementById('create').onclick=createRoom;document.getElementById('joinCode').onclick=()=>joinRoom(document.getElementById('roomCode').value.trim().toUpperCase());}}
async function createRoom(){if(!supabase)return; const {data:{user}}=await supabase.auth.getUser(); const id=user?.id||crypto.randomUUID(); const c=code(); const {data,error}=await supabase.from('rooms').insert({code:c,host_id:id}).select().single(); if(error)return alert(error.message); await showName(c,true,id,data);}
async function joinRoom(c){if(!supabase)return;if(!/^[A-Z0-9]{5}$/.test(c))return alert('Enter a 5-character room code.');const {data,error}=await supabase.from('rooms').select('*').eq('code',c).maybeSingle();if(error||!data)return alert('Room not found.');const {data:{user}}=await supabase.auth.getUser();await showName(c,false,user?.id||crypto.randomUUID(),data);}
async function showName(c,host,userId,room){const name=prompt('Enter your name to join this room:');if(!name||!name.trim())return;const existing=await supabase.from('participants').select('*').eq('room_id',room.id).order('created_at');if(existing.error)return alert(existing.error.message);let color=colors[(existing.data||[]).length%colors.length];const p=await supabase.from('participants').insert({room_id:room.id,user_id:userId,name:name.trim().slice(0,40),color}).select().single();if(p.error)return alert(p.error.message);state.room=room;state.me=p.data;state.isHost=host;await enterRoom();}
async function enterRoom(){const [people,q]=await Promise.all([supabase.from('participants').select('*').eq('room_id',state.room.id).order('created_at'),supabase.from('queue_items').select('*').eq('room_id',state.room.id).order('position')]);state.people=people.data||[];state.queue=q.data||[];const fresh=await supabase.from('rooms').select('*').eq('id',state.room.id).single();state.room=fresh.data||state.room;renderRoom();await setupRealtime();loadYouTubeAPI();}
async function setupRealtime(){state.channel=supabase.channel(`room-${state.room.id}`,{config:{broadcast:{self:true}}});state.channel.on('broadcast',{event:'state'},({payload})=>{if(payload.type==='queue'){state.queue=payload.queue||[];renderRoom();}if(payload.type==='people'){state.people=payload.people||[];renderRoom();}if(payload.type==='playback'&&!state.isHost){applyRemotePlayback(payload);}}).on('postgres_changes',{event:'*',schema:'public',table:'participants',filter:`room_id=eq.${state.room.id}`},refreshPeople).on('postgres_changes',{event:'*',schema:'public',table:'queue_items',filter:`room_id=eq.${state.room.id}`},refreshQueue).subscribe();}
async function refreshPeople(){const r=await supabase.from('participants').select('*').eq('room_id',state.room.id).order('created_at');state.people=r.data||[];renderRoom();}
async function refreshQueue(){const r=await supabase.from('queue_items').select('*').eq('room_id',state.room.id).order('position');state.queue=r.data||[];renderRoom();}
async function broadcast(type,payload={}){if(state.channel)await state.channel.send({type:'broadcast',event:'state',payload:{type,...payload}});}
function renderRoom(){const q=state.queue;const current=state.room.current_video_id;app.innerHTML=`<div class="wrap"><div class="top"><div><div class="brand">ALAMKAROK</div><div class="small">Room <b>${esc(state.room.code)}</b> • ${state.people.length} people</div></div><div class="actions"><span class="badge"><span class="dot" style="background:${esc(state.me.color)}"></span>${esc(state.me.name)}</span><button class="btn" id="showQr">QR</button></div></div><div class="roomgrid"><section><div class="card"><div class="player"><div id="player" class="playerbox"></div></div><div class="controls"><button class="control" id="prev" title="Previous">⏮</button><button class="control main" id="play" title="Play/Pause">▶</button><button class="control" id="next" title="Next">⏭</button></div><div class="small" id="playState">${state.room.is_playing?'Playing':'Paused'} • ${current?'Current video':'No video selected'}</div></div><div class="card" style="margin-top:16px"><div class="section-title"><h2>Shared Queue (${q.length})</h2><button class="btn green" id="shuffle">🔀 Shuffle</button></div><div class="row"><input class="input" id="url" placeholder="Paste a YouTube link"><button class="btn primary" id="add">Add to Queue</button></div><div style="height:12px"></div><div class="queue">${q.length?q.map((x,i)=>`<div class="qitem ${x.video_id===current?'now':''}"><div class="qnum">${i+1}</div><img class="thumb" src="${esc(x.thumbnail||ytThumb(x.video_id))}" alt=""><div style="min-width:0"><div class="qtitle">${esc(x.title||'YouTube video')}</div><div class="meta">${x.video_id===current?'NOW PLAYING • ':''}${esc(personName(x.added_by))}</div></div><div class="actions">${state.isHost?`<button class="action-sm" data-play="${esc(x.id)}">Play</button>`:''}<button class="action-sm" data-del="${esc(x.id)}">×</button></div></div>`).join(''):'<div class="empty">No videos yet. Add the first YouTube link.</div>'}</div></div></section><aside><div class="card"><div class="section-title"><h2>People in Room</h2><span class="badge">${state.isHost?'HOST':''}</span></div><div class="people">${state.people.map(p=>`<div class="person"><span class="dot" style="background:${esc(p.color)}"></span><span>${esc(p.name)}${p.id===state.me.id?' (You)':''}${p.user_id===state.room.host_id?' 👑':''}</span></div>`).join('')}</div></div><div class="card" style="margin-top:16px"><div class="section-title"><h2>Room QR</h2></div><div id="qr" class="qr"></div><div class="small" style="text-align:center;margin-top:10px">Scan to join</div><div class="linkbox" style="margin-top:10px">${esc(roomUrl(state.room.code))}</div></div></aside></div><div class="footer">Everyone can add links and control playback. Only the host displays the YouTube player.</div></div>`;
 document.getElementById('add').onclick=addLink;document.getElementById('shuffle').onclick=shuffleQueue;document.getElementById('prev').onclick=()=>command('previous');document.getElementById('next').onclick=()=>command('next');document.getElementById('play').onclick=()=>command(state.room.is_playing?'pause':'play');document.getElementById('showQr').onclick=()=>alert(roomUrl(state.room.code));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>removeItem(b.dataset.del));document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>playQueueItem(b.dataset.play));if(window.QRCode){new QRCode(document.getElementById('qr'),{text:roomUrl(state.room.code),width:150,height:150});}updatePlayButton();}
function personName(id){const p=state.people.find(x=>x.id===id);return p?p.name:'Unknown';}
async function addLink(){const input=document.getElementById('url');const id=ytId(input.value.trim());if(!id)return alert('Enter a valid YouTube link.');const max=state.queue.length?Math.max(...state.queue.map(x=>x.position))+1:0;const r=await supabase.from('queue_items').insert({room_id:state.room.id,video_id:id,title:`YouTube video ${id}`,thumbnail:ytThumb(id),added_by:state.me.id,position:max}).select().single();if(r.error)return alert(r.error.message);input.value='';await refreshQueue();await broadcast('queue',{queue:state.queue});}
async function removeItem(id){const r=await supabase.from('queue_items').delete().eq('id',id);if(r.error)return alert(r.error.message);await refreshQueue();await normalizePositions();await broadcast('queue',{queue:state.queue});}
async function normalizePositions(){for(let i=0;i<state.queue.length;i++)await supabase.from('queue_items').update({position:i}).eq('id',state.queue[i].id);const r=await supabase.from('queue_items').select('*').eq('room_id',state.room.id).order('position');state.queue=r.data||[];}
async function shuffleQueue(){if(state.queue.length<2)return;const current=state.room.current_video_id;let rest=state.queue.filter(x=>x.video_id!==current);for(let i=rest.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[rest[i],rest[j]]=[rest[j],rest[i]];}const ordered=current?[state.queue.find(x=>x.video_id===current),...rest]:rest;for(let i=0;i<ordered.length;i++)await supabase.from('queue_items').update({position:i}).eq('id',ordered[i].id);await refreshQueue();await broadcast('queue',{queue:state.queue});}
async function playQueueItem(id){const x=state.queue.find(q=>q.id===id);if(!x)return;await setRoom({current_video_id:x.video_id,current_index:state.queue.indexOf(x),is_playing:true,position_seconds:0});await broadcast('playback',{action:'load',videoId:x.video_id,position:0,playing:true});if(state.isHost)loadVideo(x.video_id,0,true);}
async function command(action){if(!state.queue.length)return;let idx=state.room.current_index??0;if(action==='next')idx=Math.min(state.queue.length-1,idx+1);if(action==='previous')idx=Math.max(0,idx-1);if(action==='play'||action==='pause'){const playing=action==='play';await setRoom({is_playing:playing,position_seconds:state.player&&state.player.getCurrentTime?state.player.getCurrentTime():state.room.position_seconds});await broadcast('playback',{action,position:state.room.position_seconds});if(state.isHost)applyLocalPlay(playing);return;}const x=state.queue[idx];await setRoom({current_video_id:x.video_id,current_index:idx,is_playing:true,position_seconds:0});await broadcast('playback',{action:'load',videoId:x.video_id,position:0,playing:true});if(state.isHost)loadVideo(x.video_id,0,true);}
async function setRoom(p){const r=await supabase.from('rooms').update({...p,updated_at:new Date().toISOString()}).eq('id',state.room.id).select().single();if(r.error)console.warn(r.error);else state.room=r.data;renderRoom();}
function loadYouTubeAPI(){if(state.videoApiReady)return;if(window.YT&&window.YT.Player){state.videoApiReady=true;initPlayer();return;}const old=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{state.videoApiReady=true;initPlayer();if(old)old();};const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';document.head.appendChild(s);}
function initPlayer(){if(!state.isHost)return;state.player=new YT.Player('player',{videoId:state.room.current_video_id||'',playerVars:{playsinline:1,controls:1,rel:0},events:{onReady:()=>{state.playerReady=true;if(state.room.current_video_id)state.player.cueVideoById(state.room.current_video_id);},onStateChange:async e=>{if(e.data===YT.PlayerState.ENDED){await command('next');}else if(e.data===YT.PlayerState.PLAYING){await setRoom({is_playing:true,position_seconds:state.player.getCurrentTime()});await broadcast('playback',{action:'sync',videoId:state.room.current_video_id,position:state.player.getCurrentTime(),playing:true});}else if(e.data===YT.PlayerState.PAUSED){await setRoom({is_playing:false,position_seconds:state.player.getCurrentTime()});await broadcast('playback',{action:'sync',videoId:state.room.current_video_id,position:state.player.getCurrentTime(),playing:false});}}}});}
function loadVideo(id,pos,play){if(!state.playerReady)return;state.player.loadVideoById({videoId:id,startSeconds:pos||0});if(!play)state.player.pauseVideo();}
function applyLocalPlay(play){if(!state.playerReady)return;play?state.player.playVideo():state.player.pauseVideo();}
function applyRemotePlayback(p){if(state.isHost)return;if(p.action==='sync'){state.room.is_playing=!!p.playing;state.room.current_video_id=p.videoId||state.room.current_video_id;state.room.position_seconds=p.position||0;renderRoom();return;}if(p.action==='load'){state.room.current_video_id=p.videoId;state.room.is_playing=!!p.playing;state.room.position_seconds=p.position||0;renderRoom();}else if(p.action==='play'){state.room.is_playing=true;renderRoom();}else if(p.action==='pause'){state.room.is_playing=false;renderRoom();}}
if(sbReady){supabase.auth.getSession().then(async({data})=>{if(!data.session)await supabase.auth.signInAnonymously();const c=new URLSearchParams(location.search).get('room');if(c)joinRoom(c.toUpperCase());else renderHome();});}else renderHome();
